name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     #- uses: actions/checkout@v3

  #     - name: Run a one-line script
  #       run: echo Hello, world!

  #     - name: Run a multi-line script
  #       run: |
  #         echo Add other actions to build,
  #         echo test, and deploy your project.
  test:
    runs-on: ubuntu-latest
    environment: 'main'
    steps:
      # - name: Secret
      #   run: echo Secret ${{ secrets.MYSECRET }}
      
      # - name: Variable
      #   run: echo ${{ vars.MYVARIABLE }}
        - name: testRun
          run: |
            echo vars.MYVARIABLE ${{ vars.MYVARIABLE }}
            echo vars.Runner ${{ vars.RUNNER }}
            echo vars.REPOSITORY_VAR  $ {{ vars.REPOSITORY_VAR  }}
            echo testEnvironment.vars.TESTVARIABLE ${{ testEnvironment.vars.TESTVARIABLE }}
            echo main.vars.TESTVARIABLE ${{ main.vars.TESTVARIABLE }}
            echo xxx $ {{ xxx }}

